title = "waffle-bot example configuration"

[bot]
# Add your own bot token inside the quotation marks in the line below
token = ''
prefix = 'waf '
extensions = ['music', 'moderation', 'errors']

[config]
#autorole = 'Member'
#dj = 'DJ'
#log_channel = 'mod-log'
#welcome_channel = 'welcome-leave'
#mute = 'Edgelord'

[database]
# Period of time in between checking for tasks
check_interval = 3600
uri = 'sqlite+aiosqlite:///waffle.db'
